### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by ghost** [ianmiell/docker-101-tutorial#1]
ShutIt Started... 
--training implies --walkthrough, setting --walkthrough on!

Loading configs...
2016-06-02 15:46:56,456 INFO: Correcting insecure file permissions on: configs/build.cnf
2016-06-02 15:46:56,540 INFO: ShutIt modules loaded
2016-06-02 15:46:56,559 INFO: Configuration loaded
Traceback (most recent call last):
  File "/usr/local/bin/shutit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/shutit_main.py", line 572, in main
    conn_target(shutit)
  File "/usr/local/lib/python2.7/dist-packages/shutit_main.py", line 166, in conn_target
    conn_module.build(shutit)
  File "/usr/local/lib/python2.7/dist-packages/shutit_module.py", line 58, in wrapper
    ret = func(self, shutit)
  File "/usr/local/lib/python2.7/dist-packages/shutit_setup.py", line 321, in build
    self.setup_host_child()
  File "/usr/local/lib/python2.7/dist-packages/shutit_setup.py", line 64, in setup_host_child
    shutit_pexpect_session.setup_prompt('origin_prompt', prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line 287, in setup_prompt
    _ = self.init_pexpect_session_environment(prefix)
  File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line 2527, in init_pexpect_session_environment
    self.get_distro_info()
  File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line 1473, in get_distro_info
    d = self.lsb_release()
  File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line 827, in lsb_release
    d['install_type'] = (package_map.INSTALL_TYPE_MAP[dist_string.lower()])
KeyError: 'linuxmint'

**Comment by ianmiell** [comment]
Hi!

Thanks for trying ShutIt/docker-101.

I see you're using linux mint (and this seems to be the cause of the error)
- do you know of a good Vagrant VM I can test this on, or I shall I just
  hunt for one?

Ian

On Thu, Jun 2, 2016 at 1:48 PM, Valentin Buza notifications@github.com
wrote:

> ShutIt Started...
> --training implies --walkthrough, setting --walkthrough on!
> 
> Loading configs...
> 2016-06-02 15:46:56,456 INFO: Correcting insecure file permissions on:
> configs/build.cnf
> 2016-06-02 15:46:56,540 INFO: ShutIt modules loaded
> 2016-06-02 15:46:56,559 INFO: Configuration loaded
> Traceback (most recent call last):
> File "/usr/local/bin/shutit", line 11, in
> sys.exit(main())
> File "/usr/local/lib/python2.7/dist-packages/shutit_main.py", line 572, in
> main
> conn_target(shutit)
> File "/usr/local/lib/python2.7/dist-packages/shutit_main.py", line 166, in
> conn_target
> conn_module.build(shutit)
> File "/usr/local/lib/python2.7/dist-packages/shutit_module.py", line 58,
> in wrapper
> ret = func(self, shutit)
> File "/usr/local/lib/python2.7/dist-packages/shutit_setup.py", line 321,
> in build
> self.setup_host_child()
> File "/usr/local/lib/python2.7/dist-packages/shutit_setup.py", line 64, in
> setup_host_child
> shutit_pexpect_session.setup_prompt('origin_prompt', prefix=prefix)
> File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line 287,
> in setup_prompt
> _ = self.init_pexpect_session_environment(prefix)
> File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line
> 2527, in init_pexpect_session_environment
> self.get_distro_info()
> File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line
> 1473, in get_distro_info
> d = self.lsb_release()
> File "/usr/local/lib/python2.7/dist-packages/shutit_pexpect.py", line 827,
> in lsb_release
> d['install_type'] = (package_map.INSTALL_TYPE_MAP[dist_string.lower()])
> KeyError: 'linuxmint'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ianmiell/docker-101-tutorial/issues/1, or mute the
> thread
> https://github.com/notifications/unsubscribe/AGrczZCmzvS4MDIhnm221iqIeOKsUeFqks5qHtEOgaJpZM4IshIv
> .

## 

My book on Docker in Practice: Get 39% off with the code 39miell
http://manning.com/miell/?a_aid=zwischenzugs&a_bid=e0d48f62

**Comment by ghost** [comment]
Hello,

No, I don't. But here is some info. 

> uname -a
> Linux kiwi 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> lsb_release -a
> No LSB modules are available.
> Distributor ID: LinuxMint
> Description:    Linux Mint 17.3 Rosa
> Release:    17.3
> Codename:   rosa
> docker --version
> Docker version 1.6.2, build 7c8fca2
> shutit version
> ShutIt Started... ShutIt version: 0.9.174

Ty,
Vali

**Comment by ianmiell** [comment]
BTW a workaround is to add the --distro arg to the shutit command in the run.sh '$SHUTIT build' line, eg

$SHUTIT build --distro debian

in your case

  --distro {ubuntu,debian,alpine,steamos,red hat,centos,fedora,shutit}
                        Specify the distro type

**Comment by ianmiell** [comment]
Tested, fixed and pushed 0.9.175
Let me know if it works for you.

**Comment by ghost** [comment]
It works now, thank you for your prompt response.
