### ISSUE TITLE
Adapt for Hypervisor.framework

### ISSUE THREAD

**Issue by hajdbo** [ianmiell/docker-101-tutorial#2]
Docker beta uses native virtualization (Hypervisor.framework on Mac, Hyper-V on Windows) rather than VirtualBox.

**Comment by ianmiell** [comment]
Docker for Mac beta doesn't work natively on my Mac, so I can't test :/
I raised a defect with Docker a while ago with debug, nothing heard back.

On Sat, Jun 4, 2016 at 8:28 PM, Boris Hajduk notifications@github.com
wrote:

> Docker beta uses native virtualization (Hypervisor.framework on Mac,
> Hyper-V on Windows) rather than VirtualBox.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ianmiell/docker-101-tutorial/issues/2, or mute the
> thread
> https://github.com/notifications/unsubscribe/AGrczfZ8y7mLMhlQ40DP-61kJvJ1gEczks5qIdHfgaJpZM4IuM0k
> .

## 

My book on Docker in Practice: Get 39% off with the code 39miell
http://manning.com/miell/?a_aid=zwischenzugs&a_bid=e0d48f62
